config/routes.rb
Rails.application.routes.draw do


  # Devise routes

  devise_for :players, controllers: { registrations: 'registrations' }

  devise_scope :player do
    post "players/sign_up", to: "devise/sessions#new", as: :sign_up
    post "login", to: "devise/sessions#create", as: :login
    delete "logout", to: "devise/sessions#destroy", as: :logout
  end

  patch "players", to: "registrations#update"


  # Players routes

  root to: "players#home"
  get "players", to: "players#index"
  get "players/:id", to: "players#show", as: :player


  # Games routes

  get "games", to: "games#menu"

  get "games/new_game", to: "games#new_game"
  post "games/create_game", to: "games#create_game", as: "create_game"

  get "games/:id", to: "games#show", as: :game


  # Officials in the Games routes

  get "games/officials_in_the_game/:game_id", to: "officials_in_the_game#officials_in_the_game", as: :games_officials_in_the_game
  post "games/create_officials_in_the_game", to: "officials_in_the_game#create_officials_in_the_game", as: :create_officials_in_the_game

  post 'update_chosen_players', to: 'officials_in_the_game#update_chosen_players'
  get 'current_chosen_players', to: 'officials_in_the_game#current_chosen_players'
  get 'refresh_selectbox', to: 'officials_in_the_game#refresh_selectbox'
  post 'remove_chosen_player_from_temporary_array', to: 'officials_in_the_game#remove_chosen_player_from_temporary_array'



  # Rooster routes

  get "games/rooster", to: "games#rooster"


end



  # rota root
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root to: "pages#home"

app/models/officials_in_the_game.rb
class OfficialsInTheGame < ApplicationRecord
  belongs_to :game
  belongs_to :official_position
  belongs_to :player
end

app/controllers/officials_in_the_game_controller.rb
class OfficialsInTheGameController < ApplicationController

  before_action :set_temporary_chosen_players_array

  def set_temporary_chosen_players_array

    # session[:temporary_chosen_players_array] = []

    @temporary_chosen_players_array = session[:temporary_chosen_players_array] || []

  end

  ########################################

  def officials_in_the_game
    @game_show = Game.find(params[:game_id])

    @players = Player.all

    @official_position = OfficialPosition.all

    @officials_in_the_game = OfficialsInTheGame.where(game_id: @game_show.id)

    @lista_filtrada = lista_filtrada

    @jogadoras_selecionadas = Player.where(id: @temporary_chosen_players_array) || []

  end

  def create_officials_in_the_game
    # o nome mais adequado para esse método seria algo como create_or_update
    # mudar o nome dessa classe aqui e onde precisar

    # Encontra ou inicializa um registro para o jogo e a posição oficial
    @official = OfficialsInTheGame.find_or_initialize_by(
      game_id: officials_in_the_game_params[:game_id],
      official_position_id: officials_in_the_game_params[:official_position_id]
      )

      # Atualiza o registro com os parâmetros fornecidos
      @official.assign_attributes(officials_in_the_game_params)

      if @official.save
        flash[:notice] = "Equipe de arbitragem salva com sucesso!"
        redirect_to game_path(@official.game_id)
      else
        flash.now[:alert] = "Não foi possível salvar a equipe de arbitragem."
        render :officials_in_the_game
      end
  end

  #######################################



  def lista_filtrada
    # @temporary_chosen_players_array = [] if @temporary_chosen_players_array.nil?
    Player.all.reject { |player| @temporary_chosen_players_array.include?(player.id) }
  end

  def update_chosen_players
    chosen_player_id = params[:chosen_player_id].to_i

    Rails.logger.debug "ID da jogadora recebida: #{chosen_player_id}" # Adicione esta linha


    add_chosen_player_to_temporary_array(chosen_player_id)

    render json: { success: true }
  end

  def add_chosen_player_to_temporary_array(chosen_player_id)
    # chosen_player_id = chosen_player_id.to_i
    return if player_exists?(chosen_player_id)

    @temporary_chosen_players_array << chosen_player_id
    session[:temporary_chosen_players_array] = @temporary_chosen_players_array
  end

  def remove_chosen_player_from_temporary_array(chosen_player_id)
    return unless player_exists?(chosen_player_id)

    @temporary_chosen_players_array.delete(chosen_player_id)
    session[:temporary_chosen_players_array] = @temporary_chosen_players_array
  end

  def player_exists?(player_id)
    @temporary_chosen_players_array.include?(player_id)
  end

  def current_chosen_players

    @jogadoras_selecionadas = Player.where(id: @temporary_chosen_players_array) #.select(:calling_name, :derby_number)

    render partial: 'shared/pill_container_display', layout: false #, locals: { jogadoras_selecionadas: @jogadoras_selecionadas }


  end

  def update_pill_display



  end

  def refresh_selectbox
    render partial: 'shared/selectbox' #, locals: { lista_filtrada: lista_filtrada }
    # render plain: "carregado"
  end




  def remove_chosen_player_from_temporary_array

    player_to_be_deleted = params[:player_id].to_i
    @temporary_chosen_players_array.delete(player_to_be_deleted)
    head :ok

  end



  private

  def officials_in_the_game_params
    params.require(:officials_in_the_game).permit(:game_id, :official_position_id, :player_id, :is_shadowing)
  end


end

app/views/officials_in_the_game/officials_in_the_game.html copy.erb
<%# novos testes de layout %>

<%= simple_form_for :player_selection do |f| %>

  <%= f.input :player_id,
              collection: @players,
              label_method: :calling_name,
              value_method: :id,
              include_blank: "digite",
              input_html: { id: 'select-box',
                            onchange: 'addPlayer(this.value)' } %>

<% end %>








<%# testando css do card %>
<div class="container">
  <div class="row">
    <div class="col-6">
      <div class="card-select-official-in-the-game">
        <img class="img-squared-avatar" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSn5Lj_iuoQmSpl3BB4QQpx7P-LMLAyq1LHaw&s" >

        <div class="info-container">
          <div class="box-player-info">
            Jogadora
          </div>

          <div class="box-official-position">
            Posição
          </div>

        </div>
      </div>
    </div>

        <div class="col-6">
      <div class="card-select-official-in-the-game">
        <img class="img-squared-avatar" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSn5Lj_iuoQmSpl3BB4QQpx7P-LMLAyq1LHaw&s" >

        <div class="info-container">
          <div class="box-player-info-rosa">
            Jogadora
          </div>

          <div class="box-official-position-rosa">
            Posição
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<br><br><br>

<%# Simplificado com grid %>
<div class="container">
  <div class="row">

    <% # Define os grupos com base na presença de "Referee" no nome da posição %>
    <% official_positions_grouped_by_referee_or_nsoXXX = @official_position.group_by { |position| position.official_position.include?("Referee") ? "Referee" : "NSO" } %>

    <% # Loop para criar duas colunas %>
    <% official_positions_grouped_by_referee_or_nsoXXX.each do |official_category, official_positions| %>
      <div class="col-6">
        <div class="border border-5">

          <% official_positions.each do |position| %>

            <% player_assigned_as_official = @officials_in_the_game.find { |o| o.official_position_id == position.id } || OfficialsInTheGame.new(game_id: @game_show.id, official_position_id: position.id) %>

            <div class="border border-3 border-primary my-3">
              <div class="cards card-ref">
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSn5Lj_iuoQmSpl3BB4QQpx7P-LMLAyq1LHaw&s" alt="foto" width="120px" height="120px">

                <%= simple_form_for player_assigned_as_official, url: create_officials_in_the_game_path, method: :post do |f| %>
                  <div class="card-ref-data">
                    <%= f.input :player_id,
                      collection: Player.all.map { |player| [player.calling_name, player.id] },
                      selected: player_assigned_as_official.player_id,
                      prompt: "Selecione uma jogadora",
                      label: "#{position.official_position}",
                      input_html: { onchange: 'this.form.submit()' } %>

                    <%= f.hidden_field :game_id, value: @game_show.id %>
                    <%= f.hidden_field :official_position_id, value: position.id %>
                    <%= f.hidden_field :is_shadowing, value: false %>
                  </div>
                <% end %>
              </div>
            </div>

          <% end %>

        </div>
      </div>
    <% end %>

  </div>
</div>


<div class="container">
  <div class="row">

    <% official_positions_grouped_by_referee_or_nso = @official_position.group_by { |position| position.official_position.include?("Referee") ? "Referee" : "NSO" } %>

      <% official_positions_grouped_by_referee_or_nso.each do |official_category, official_positions| %>

        <div class="col-6">

            <% official_positions.each do |position| %>

              <div class="card-select-official-in-the-game">

                <% player_assigned_as_official = @officials_in_the_game.find { |o| o.official_position_id == position.id } || OfficialsInTheGame.new(game_id: @game_show.id, official_position_id: position.id) %>

                  <img  class="img-squared-avatar" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSn5Lj_iuoQmSpl3BB4QQpx7P-LMLAyq1LHaw&s">

                          <div class="info-container">

                            <%= simple_form_for player_assigned_as_official, url: create_officials_in_the_game_path, method: :post do |f| %>

                              <div class="box-player-info">
                                <%= f.input :player_id,
                                    collection: Player.all.map { |player| [player.calling_name, player.id] },
                                    selected: player_assigned_as_official.player_id,
                                    prompt: "Selecione uma jogadora",
                                    label: false,
                                    input_html: { onchange: 'this.form.submit()', class: 'select-box-limpa' }

                                %>

                                <%=
                                    f.hidden_field :game_id, value: @game_show.id
                                    f.hidden_field :official_position_id, value: position.id
                                    f.hidden_field :is_shadowing, value: false
                                %>

                              </div>

                              <div class="box-official-position">
                                <%= position.official_position %>
                              </div>
                            <% end %>
                          </div>
              </div>

            <% end %>

        </div>

      <% end %>
  </div>
</div>

app/views/officials_in_the_game/officials_in_the_game.html.erb
<%# app/views/officials_in_the_game/officials_in_the_game.html.erb %>
<head>
    <%= javascript_include_tag 'officials_in_the_game'  %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
</head>

<body>

  <div class="mobile_view_container">
<!-- Adicionando uma imagem de fundo ao cabeçalho -->

    <div class="header-image"></div> <!-- Contêiner com a imagem de fundo -->



    <div class="content">
        <%= render 'shared/selectbox' %>
        <%= render 'shared/pill_container_display' %>
    </div>


</body>