config/routes.rb
Rails.application.routes.draw do


  # Devise routes

  devise_for :players, controllers: { registrations: 'registrations' }

  devise_scope :player do
    post "players/sign_up", to: "devise/sessions#new", as: :sign_up
    post "login", to: "devise/sessions#create", as: :login
    delete "logout", to: "devise/sessions#destroy", as: :logout
  end

  patch "players", to: "registrations#update"


  # Players routes

  root to: "players#home"
  get "players", to: "players#index"
  get "players/:id", to: "players#show", as: :player


  # Games routes

  get "games", to: "games#menu"

  get "games/new_game", to: "games#new_game"
  post "games/create_game", to: "games#create_game", as: "create_game"

  get "games/:id", to: "games#show", as: :game


  # Officials in the Games routes

  get "games/officials_in_the_game/:game_id", to: "officials_in_the_game#officials_in_the_game", as: :games_officials_in_the_game
  post "games/create_officials_in_the_game", to: "officials_in_the_game#create_officials_in_the_game", as: :create_officials_in_the_game

  post 'update_chosen_players', to: 'officials_in_the_game#update_chosen_players'
  get 'current_chosen_players', to: 'officials_in_the_game#current_chosen_players'
  get 'refresh_selectbox', to: 'officials_in_the_game#refresh_selectbox'
  post 'remove_chosen_player_from_temporary_array', to: 'officials_in_the_game#remove_chosen_player_from_temporary_array'



  # Rooster routes

  get "games/rooster", to: "games#rooster"


end



  # rota root
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root to: "pages#home"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  before_create :game_creation_default_status

  has_many :leagues_in_the_games
  has_many :officials_in_the_games
  has_many :roosters
  has_many :jams
  has_many :penalty_trackings


  private

  def game_creation_default_status
    self.game_is_over = false
  end

end

app/models/jam.rb
class Jam < ApplicationRecord
  belongs_to :game
  belongs_to :line_up
  belongs_to :jam_finished_by
  has_many :penalty_trackings
end

app/models/jam_finished_by.rb
class JamFinishedBy < ApplicationRecord
  has_many :jams
end

app/models/league.rb
class League < ApplicationRecord
  has_many :leagues_in_the_games
  has_many :players_in_the_leagues
end

app/models/league_in_the_game.rb
class LeagueInTheGame < ApplicationRecord
  belongs_to :league
  belongs_to :game
end

app/models/leagues_in_the_game.rb
class LeaguesInTheGame < ApplicationRecord
  belongs_to :league
  belongs_to :game
end

app/models/line_up.rb
class LineUp < ApplicationRecord
  belongs_to :jammer_a
  belongs_to :pivot_a
  belongs_to :blocker1_a
  belongs_to :blocker2_a
  belongs_to :blocker3_a
  belongs_to :jammer_b
  belongs_to :pivot_b
  belongs_to :blocker1_b
  belongs_to :blocker2_b
  belongs_to :blocker3_b

  has_many :jams
end

app/models/official_position.rb
class OfficialPosition < ApplicationRecord
  has_many :officials_in_the_games

end

app/models/officials_in_the_game.rb
class OfficialsInTheGame < ApplicationRecord
  belongs_to :game
  belongs_to :official_position
  belongs_to :player
end

app/models/penalty.rb
class Penalty < ApplicationRecord
  has_many :penalty_trackings

end

app/models/penalty_tracking.rb
class PenaltyTracking < ApplicationRecord
  belongs_to :jam
  belongs_to :game
  belongs_to :player
  belongs_to :penalty
end

app/models/player.rb
class Player < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :players_in_the_leagues
  has_many :players_in_the_roosters
  has_many :officials_in_the_games
  has_many :penalty_trackings

end

app/models/player_in_the_league.rb
class PlayerInTheLeague < ApplicationRecord
  belongs_to :player
  belongs_to :league
end

app/models/players_in_the_league.rb
class PlayersInTheLeague < ApplicationRecord
  belongs_to :player
  belongs_to :league
end

app/models/players_in_the_rooster.rb
class PlayerInTheRooster < ApplicationRecord
  belongs_to :rooster
  belongs_to :player

  has_many :jammer_a, class_name: 'LineUp', foreign_key: 'jammer_a_id'
  has_many :pivot_a, class_name: 'LineUp', foreign_key: 'pivot_a_id'
  has_many :blocker1_a, class_name: 'LineUp', foreign_key: 'blocker1_a_id'
  has_many :blocker2_a, class_name: 'LineUp', foreign_key: 'blocker2_a_id'
  has_many :blocker3_a, class_name: 'LineUp', foreign_key: 'blocker3_a_id'
  has_many :jammer_b, class_name: 'LineUp', foreign_key: 'jammer_b_id'
  has_many :pivot_b, class_name: 'LineUp', foreign_key: 'pivot_b_id'
  has_many :blocker1_b, class_name: 'LineUp', foreign_key: 'blocker1_b_id'
  has_many :blocker2_b, class_name: 'LineUp', foreign_key: 'blocker2_b_id'
  has_many :blocker3_b, class_name: 'LineUp', foreign_key: 'blocker3_b_id'

end

app/models/rooster.rb
class Rooster < ApplicationRecord
  belongs_to :game
  has_many :players_in_the_roosters
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def menu
    # Game.first.destroy
    @old_games = Game.where(game_is_over: true)
    @open_games = Game.where(game_is_over: false)
    @games = Game.all
  end

  def show
    @game_show = Game.find(params[:id])

  end

####################################

  def new_game
    @new_game = Game.new
  end

  def create_game
    @new_game = Game.new(game_params)
    @game_creator = current_player
    # Atenção!
    # é preciso fazer uma migration para incluir o game_creator ou game_owner na tabela games

    if @new_game.save
      flash.now[:notice] = "Novo jogo criado com sucesso!"
      redirect_to game_path(@new_game)
    else
      flash.now[:alert] = "Não foi possível criar um novo jogo."
      render :new_game
    end
  end


 private

  def game_params
    params.require(:game).permit(:game_date, :game_time, :game_location_nickname, :game_map_address, :game_is_over)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Space Jammer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>


    <%# Tudo esse código é pra fazer funcionar o Simple Form For %>

    <!-- Adicione as folhas de estilo do jQuery UI -->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <!-- Adicione o jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Adicione o jQuery UI -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script>
    $(document).ready(function() {
      $('.datepicker').datepicker();
    });
    </script>

    <%# até aqui %>

  </head>


  <body>
   <%#  <p class="notice"><%= notice </p>
    <%# < class="alert"><%= alert %>
    <%= render "shared/flashes" %>
    <div class="fixed-nav">
      <%= render "shared/navbar" %>
    </div>
    <div class="body-nav" data-controller="hello">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-nav">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <% if player_signed_in? %>
          <%# <li class="nav-item active"> %>
           <%#  <%= link_to "Home", "#", class: "nav-link" %>
          <%# </li> %>
          <%# <li class="nav-item"> %>
           <%#  <%= link_to "Messages", "#", class: "nav-link" %>
         <%#  </li> %>
         <%#  <li> %>
            <%# <%= link_to "Logout", logout_path, method: :delete, data: { confirm: "Tem certeza que deseja sair?" } %>
         <%#
       <%#      <%= link_to "Login", new_player_session_path, class: "btn btn-primary" %>
            <div class="menu">
              <%= link_to "Edit", edit_player_registration_path(current_player), class: "btn-helper" %>
              <%= form_tag(logout_path, method: :delete, class: "form") do %>
                <%= submit_tag "Logout" %>
              <% end %>
            </div>
          <%# <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
         <%#  </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%# <%= link_to "Another action", "#", class: "dropdown-item" %>
             <%#  <%= link_to "Log out", destroy_player_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            <%# /div> %>
         <%# </li> %>
        <% else %>
          <div class="menu">
            <%= link_to "Sign Up", new_player_registration_path, class: "btn-helper" %>
            <%= form_tag(login_path, method: :post, class: "form") do %>
              <%= submit_tag "Login" %>
            <% end %>
          </div>
          <%# <li class="nav-item"> %>
           <%#  <%= link_to "Login", new_player_session_path, class: "nav-link" %>
          <%# </li> %>
        <% end %>
    </div>
  </div>
</div>

app/views/shared/_pill_container_display.html.erb
<%# _pill_container_display.html.erb %>

  <div id="pill-container-display">
    <% @jogadoras_selecionadas.each do |jogadora_selecionada| %>
      <span class="pill pill--selected" type="button">
        <%= "#{jogadora_selecionada.calling_name} ##{jogadora_selecionada.derby_number}" %>
        <button class="x-remove-pill-button">x</button>
      </span>
    <% end %>
  </div>

app/views/shared/_selectbox.html.erb
<%# _selectbox.html.erb %>
<%= simple_form_for :player_selection do |f| %>

  <%= f.input :player_id,
              collection: Player.all.reject { |player| @temporary_chosen_players_array.include?(player.id) },
              # collection: @lista_filtrada,


              label_method: :calling_name,
              value_method: :id,
              include_blank: "digite",
              input_html: { id: 'playerSelectBox',
                            class: 'selectbox',
                            onchange: 'addPlayer(this.value)' } %>

<% end %>