config/routes.rb
Rails.application.routes.draw do


  # Devise routes

  devise_for :players, controllers: { registrations: 'registrations' }

  devise_scope :player do
    post "players/sign_up", to: "devise/sessions#new", as: :sign_up
    post "login", to: "devise/sessions#create", as: :login
    delete "logout", to: "devise/sessions#destroy", as: :logout
  end

  patch "players", to: "registrations#update"


  # Players routes

  root to: "players#home"
  get "players", to: "players#index"
  get "players/:id", to: "players#show", as: :player


  # Games routes

  get "games", to: "games#menu"

  get "games/new_game", to: "games#new_game"
  post "games/create_game", to: "games#create_game", as: "create_game"

  get "games/:id", to: "games#show", as: :game


  # Officials in the Games routes

  get "games/officials_in_the_game/:game_id", to: "officials_in_the_game#officials_in_the_game", as: :games_officials_in_the_game
  post "games/create_officials_in_the_game", to: "officials_in_the_game#create_officials_in_the_game", as: :create_officials_in_the_game

  post 'update_chosen_players', to: 'officials_in_the_game#update_chosen_players'
  get 'current_chosen_players', to: 'officials_in_the_game#current_chosen_players'
  get 'refresh_selectbox', to: 'officials_in_the_game#refresh_selectbox'
  post 'remove_chosen_player_from_temporary_array', to: 'officials_in_the_game#remove_chosen_player_from_temporary_array'



  # Rooster routes

  get "games/rooster", to: "games#rooster"


end



  # rota root
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root to: "pages#home"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  before_create :game_creation_default_status

  has_many :leagues_in_the_games
  has_many :officials_in_the_games
  has_many :roosters
  has_many :jams
  has_many :penalty_trackings


  private

  def game_creation_default_status
    self.game_is_over = false
  end

end

app/models/jam.rb
class Jam < ApplicationRecord
  belongs_to :game
  belongs_to :line_up
  belongs_to :jam_finished_by
  has_many :penalty_trackings
end

app/models/jam_finished_by.rb
class JamFinishedBy < ApplicationRecord
  has_many :jams
end

app/models/league.rb
class League < ApplicationRecord
  has_many :leagues_in_the_games
  has_many :players_in_the_leagues
end

app/models/league_in_the_game.rb
class LeagueInTheGame < ApplicationRecord
  belongs_to :league
  belongs_to :game
end

app/models/leagues_in_the_game.rb
class LeaguesInTheGame < ApplicationRecord
  belongs_to :league
  belongs_to :game
end

app/models/line_up.rb
class LineUp < ApplicationRecord
  belongs_to :jammer_a
  belongs_to :pivot_a
  belongs_to :blocker1_a
  belongs_to :blocker2_a
  belongs_to :blocker3_a
  belongs_to :jammer_b
  belongs_to :pivot_b
  belongs_to :blocker1_b
  belongs_to :blocker2_b
  belongs_to :blocker3_b

  has_many :jams
end

app/models/official_position.rb
class OfficialPosition < ApplicationRecord
  has_many :officials_in_the_games

end

app/models/officials_in_the_game.rb
class OfficialsInTheGame < ApplicationRecord
  belongs_to :game
  belongs_to :official_position
  belongs_to :player
end

app/models/penalty.rb
class Penalty < ApplicationRecord
  has_many :penalty_trackings

end

app/models/penalty_tracking.rb
class PenaltyTracking < ApplicationRecord
  belongs_to :jam
  belongs_to :game
  belongs_to :player
  belongs_to :penalty
end

app/models/player.rb
class Player < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :players_in_the_leagues
  has_many :players_in_the_roosters
  has_many :officials_in_the_games
  has_many :penalty_trackings

end

app/models/player_in_the_league.rb
class PlayerInTheLeague < ApplicationRecord
  belongs_to :player
  belongs_to :league
end

app/models/players_in_the_league.rb
class PlayersInTheLeague < ApplicationRecord
  belongs_to :player
  belongs_to :league
end

app/models/players_in_the_rooster.rb
class PlayerInTheRooster < ApplicationRecord
  belongs_to :rooster
  belongs_to :player

  has_many :jammer_a, class_name: 'LineUp', foreign_key: 'jammer_a_id'
  has_many :pivot_a, class_name: 'LineUp', foreign_key: 'pivot_a_id'
  has_many :blocker1_a, class_name: 'LineUp', foreign_key: 'blocker1_a_id'
  has_many :blocker2_a, class_name: 'LineUp', foreign_key: 'blocker2_a_id'
  has_many :blocker3_a, class_name: 'LineUp', foreign_key: 'blocker3_a_id'
  has_many :jammer_b, class_name: 'LineUp', foreign_key: 'jammer_b_id'
  has_many :pivot_b, class_name: 'LineUp', foreign_key: 'pivot_b_id'
  has_many :blocker1_b, class_name: 'LineUp', foreign_key: 'blocker1_b_id'
  has_many :blocker2_b, class_name: 'LineUp', foreign_key: 'blocker2_b_id'
  has_many :blocker3_b, class_name: 'LineUp', foreign_key: 'blocker3_b_id'

end

app/models/rooster.rb
class Rooster < ApplicationRecord
  belongs_to :game
  has_many :players_in_the_roosters
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def menu
    # Game.first.destroy
    @old_games = Game.where(game_is_over: true)
    @open_games = Game.where(game_is_over: false)
    @games = Game.all
  end

  def show
    @game_show = Game.find(params[:id])

  end

####################################

  def new_game
    @new_game = Game.new
  end

  def create_game
    @new_game = Game.new(game_params)
    @game_creator = current_player
    # Atenção!
    # é preciso fazer uma migration para incluir o game_creator ou game_owner na tabela games

    if @new_game.save
      flash.now[:notice] = "Novo jogo criado com sucesso!"
      redirect_to game_path(@new_game)
    else
      flash.now[:alert] = "Não foi possível criar um novo jogo."
      render :new_game
    end
  end


 private

  def game_params
    params.require(:game).permit(:game_date, :game_time, :game_location_nickname, :game_map_address, :game_is_over)
  end

end

app/controllers/leagues_controller.rb
# class LeaguesController < ApplicationController
#   def index
#   end
# end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  before_action :require_login, only: :home

  def home
  end

  def index
    @players = Player.order(created_at: :desc)
  end

  def show
    @player = Player.find(params[:id])
  end

  # def destroy
    # @player = Player.find(params[:id])
    # @player.destroy
    # redirect_to root_path, notice: "Player deletado com sucesso."
  # end

  # def logout
    # sign_out(current_player)
    # redirect_to root_path, status: :see_other
  # end

  private

  def require_login
    unless logged_in?
      flash[:error] = "Você precisa estar logada"
      redirect_to new_player_session_path
    end
  end

  def logged_in?
    player_signed_in?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/menu.html.erb
<h1>Games#Menu</h1>
<p>Find me in app/views/games/menu.html.erb</p>

<ol>
  <li><%= link_to "Criar novo jogo", games_new_game_path %></li>

  <hr>

  <li>
    Lista de jogos em aberto
    <ul>
      <% @open_games.each do |game| %>
        <li>
          <%= link_to "ID: #{game.id}, Status: #{game.game_is_over ? 'Concluído' : 'Em andamento'}", game_path(game) %>
        </li>
      <% end %>
    </ul>
  </li>

  <hr>

  <li>
    Lista de old games
    <ul>
      <% @old_games.each do |game| %>
        <li>
          <%= "ID: #{game.id}, Status: #{game.game_is_over ? 'Concluído' : 'Em andamento'}" %>
        </li>
      <% end %>
    </ul>
  </li>

  <hr>

  <li>
    Lista de todos games (só pra teste)
    <ul>
      <% @games.each do |game| %>
        <li>
          <%# <%= "ID: #{game.id}, Status: #{game.game_is_over ? 'Concluído' : 'Em andamento'}" %>
          <%= "ID: #{game.id}, Status: #{game.game_is_over}" %>

        </li>
      <% end %>
    </ul>
  </li>
</ol>

app/views/games/new_game.html.erb
new_game.html.erb

Id deste jogo <%= @new_game.id %>

<hr>

<h4>Criar form com:</h4>

<%= form_with(model: @new_game, url: create_game_path, method: :post) do |form| %>
  <p>Data do Jogo: <%= form.date_field :game_date %></p>
  <p>Hora do Jogo: <%= form.time_field :game_time %> </p>
  <p>Nome do local do Jogo: <%= form.text_field :game_location_nickname %> </p>
  <p>Local do jogo (campo ligado so google maps?) <%= form.text_field :game_map_address %> </p>


  <%= form.submit "Salvar jogo" %>
<% end %>

<hr>

<%= simple_form_for @new_game, url: create_game_path, method: :post do |form| %>
  <%= form.input :game_date, as: :string, input_html: { class: 'datepicker' }, label: "Data do Jogo" %>
  <%= form.input :game_time, as: :time, label: "Hora do Jogo" %>
  <%= form.input :game_location_nickname, label: "Nome do local do Jogo" %>
  <%= form.input :game_map_address, label: "Local do jogo (campo ligado ao Google Maps?)" %>

  <%= form.button :submit, "Salvar jogo" %>
<% end %>

<hr>

<li><%= link_to "Menu de Jogos", games_path %></li>

app/views/games/rooster.html.erb
<h3>Crie seu rooster aqui</h3>


<p>Id do Rooster</p>

<hr>

<p>Nome do time</p>
<p>Cor</p>

<hr>

<p>Players in the rooster</p>

app/views/games/show.html.erb
show.html.erb

<%= @game_show.id%>
<p>
<%= "ID: #{@game_show.id}, Status: #{@game_show.game_is_over ? 'Concluído' : 'Em andamento'}" %>
</p>
<ul>
  <li><%= "Data: #{@game_show.game_date}" %></li>
  <li><%= "Horário: #{@game_show.game_time}" %></li>
  <li><%= "Local: #{@game_show.game_location_nickname}" %></li>
  <li><%= "Endereço: #{@game_show.game_map_address}" %></li>
  <li><%= "Concluído: #{@game_show.game_is_over}" %></li>

</ul>

<hr>

<h4>Criar botões:</h4>

<p><%= link_to "Criar Rooster do Time A", games_rooster_path %></p>
<p><%= link_to "Criar Rooster do Time B", games_rooster_path %></p>

<p><%= link_to "Escalar Ref Team", games_officials_in_the_game_path(game_id: @game_show.id) %></p>


<hr>


    Refs escalados
    <ul>
      <% @game_show.officials_in_the_games.each do |official| %>
        <li>Jogadora: <%= official.id %> - <%= official.player.calling_name %></li>
        <li>Tipo de ref: <%= official.official_position.official_position_code %> - <%= official.official_position.official_position %></li>
        <hr>
      <% end %>
    </ul>

app/views/league/index.html.erb
<h1>League#index</h1>
<p>Find me in app/views/league/index.html.erb</p>

app/views/players/home.html.erb
<ul>
  <li><%= link_to "Ver meu perfil", player_path(current_player.id) %></li>
  <li><%= link_to "Menu de Jogos", games_path %></li>
</ul>

app/views/players/index.html.erb
<ul>
  <% @players.each do |player| %>
    <li><%= link_to player.calling_name, player_path(player) %></li>
  <% end %>

</ul>

app/views/players/show.html.erb
<h2><%= @player.calling_name %> <%= @player.family_name %></h2>
<h2><%= @player.derby_name %> #<%= @player.derby_number %> </h2>
<h2>Liga <%= @player.players_in_the_leagues.last.league.league_name %> </h2>